version: '3'
services:
    b2share:
        image: eudatb2share/b2share:2.4.0
        command:
            - /eudat/b2share.sh
        environment:
            # If used with b2share configloader, add B2SHARE_ in front of every variable that does not allready have it
            - "B2ACCESS_CONSUMER_KEY=${B2ACCESS_CONSUMER_KEY}"
            - "B2ACCESS_SECRET_KEY=${B2ACCESS_SECRET_KEY}"
            - "USE_STAGING_B2ACCESS=1"
            - "B2SHARE_SECRET_KEY=xyz"
            - "B2SHARE_JSONSCHEMAS_HOST=86.50.228.13"
            - "INIT_DB_AND_INDEX=1"
            - "LOAD_DEMO_COMMUNITIES_AND_RECORDS=1"
            - "B2SHARE_PREFERRED_URL_SCHEME=https"
            - "B2SHARE_SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://b2share1:xyz@postgres:5432/b2sharedb1'"
            - "B2SHARE_CACHE_REDIS_HOST='redis'"
            - "B2SHARE_CACHE_REDIS_URL='redis://redis:6379/0'"
            - "B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://redis:6379/1'"
            - "B2SHARE_BROKER_URL='amqp://b2share1:xyz@mq:5672/'"
            - "B2SHARE_CELERY_BROKER_URL='amqp://b2share1:xyz@mq:5672/'"
            - "B2SHARE_CELERY_RESULT_BACKEND='redis://redis:6379/2'"
            - "B2SHARE_SEARCH_ELASTIC_HOSTS='elasticsearch'"
            - "B2SHARE_LOGGING_LEVEL=DEBUG"
        volumes:
            - "/data/b2share/b2share-data:/usr/var/b2share-instance"
            # - "./elasticsearch/mappings/record-view:/usr/local/lib/python3.6/site-packages/invenio_stats/contrib/record_view/v2"
            # - "./elasticsearch/mappings/file-download:/usr/local/lib/python3.6/site-packages/invenio_stats/contrib/file_download/v2"
            # - "./elasticsearch/mappings/record-view-agg:/usr/local/lib/python3.6/site-packages/invenio_stats/contrib/aggregations/aggr_record_view/v2"
        deploy:
            placement:
              constraints:
                - node.hostname==swarm-1.novalocal
        networks:
          - b2

    # b2share:
    #     extends: b2share-base
    #     command:
    #         - /eudat/b2share.sh
    #     deploy:
    #         placement:
    #           constraints:
    #             - node.hostname==swarm-1.novalocal

    mq:
        image: rabbitmq:3.8-management-alpine
        environment:
            - "RABBITMQ_DEFAULT_USER=b2share1"
            - "RABBITMQ_DEFAULT_PASS=xyz"
        volumes:
            - "/data/b2share/rabbitmq-data:/var/lib/rabbitmq"
        deploy:
            placement:
              constraints:
                - node.hostname==swarm-1.novalocal
        networks:
          - b2

    # b2share-test:
    #     extends: b2share-base
    #     environment:
    #         - "DEBUG=True"
    #         - "FLASK_ENV=Development"
    #         - "FLASK_DEBUG=1"
    #     command:
    #         - /bin/sh
    #         - -c
    #         - |
    #           # Install test-dependencies and run tests
    #           pip install -e /eudat/b2share/.[all]
    #           /eudat/b2share/run_tests.sh
    #     expose:
    #         - "5001"
    #     links:
    #         - elasticsearch
    #         - redis
    #         - postgres
    #         - mq

    # backup:
    #     build: backup
    #     environment:
    #         - "PGPASSWORD=${B2SHARE_POSTGRESQL_PASSWORD}"
    #         - "POSTGRES_USER=${B2SHARE_POSTGRESQL_USER}"
    #     volumes:
    #         - "${B2SHARE_1_DATADIR}/db_dump:/usr/local/share/pgsql_dumps"

networks:
  b2:
    external: true
